// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(jova_core_ffiFFI)
import jova_core_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_jova_core_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_jova_core_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureJovaCoreFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol JovaWalletProtocol: AnyObject, Sendable {
    
    /**
     * Derive the canonical address for the given chain and account index.
     */
    func address(chain: JovaChain, account: UInt32) throws  -> Address
    
    /**
     * Sign a message. Chain is implicit in the `SignableMessage` variant.
     */
    func signMessage(msg: SignableMessage) throws  -> Signature
    
    /**
     * Sign a transaction. For EVM, the chain ID inside the variant is authoritative.
     */
    func signTx(tx: UnsignedTx) throws  -> SignedTx
    
}
open class JovaWallet: JovaWalletProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_jova_core_ffi_fn_clone_jovawallet(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_jova_core_ffi_fn_free_jovawallet(handle, $0) }
    }

    
    /**
     * Create a wallet from a BIP-39 mnemonic phrase and optional passphrase.
     */
public static func fromMnemonic(words: String, passphrase: String)throws  -> JovaWallet  {
    return try  FfiConverterTypeJovaWallet_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_jova_core_ffi_fn_constructor_jovawallet_from_mnemonic(
        FfiConverterString.lower(words),
        FfiConverterString.lower(passphrase),$0
    )
})
}
    

    
    /**
     * Derive the canonical address for the given chain and account index.
     */
open func address(chain: JovaChain, account: UInt32)throws  -> Address  {
    return try  FfiConverterTypeAddress_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_jova_core_ffi_fn_method_jovawallet_address(
            self.uniffiCloneHandle(),
        FfiConverterTypeJovaChain_lower(chain),
        FfiConverterUInt32.lower(account),$0
    )
})
}
    
    /**
     * Sign a message. Chain is implicit in the `SignableMessage` variant.
     */
open func signMessage(msg: SignableMessage)throws  -> Signature  {
    return try  FfiConverterTypeSignature_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_jova_core_ffi_fn_method_jovawallet_sign_message(
            self.uniffiCloneHandle(),
        FfiConverterTypeSignableMessage_lower(msg),$0
    )
})
}
    
    /**
     * Sign a transaction. For EVM, the chain ID inside the variant is authoritative.
     */
open func signTx(tx: UnsignedTx)throws  -> SignedTx  {
    return try  FfiConverterTypeSignedTx_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_jova_core_ffi_fn_method_jovawallet_sign_tx(
            self.uniffiCloneHandle(),
        FfiConverterTypeUnsignedTx_lower(tx),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJovaWallet: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = JovaWallet

    public static func lift(_ handle: UInt64) throws -> JovaWallet {
        return JovaWallet(unsafeFromHandle: handle)
    }

    public static func lower(_ value: JovaWallet) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JovaWallet {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: JovaWallet, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJovaWallet_lift(_ handle: UInt64) throws -> JovaWallet {
    return try FfiConverterTypeJovaWallet.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJovaWallet_lower(_ value: JovaWallet) -> UInt64 {
    return FfiConverterTypeJovaWallet.lower(value)
}




public struct AccessListItem: Equatable, Hashable {
    public var address: String
    public var storageKeys: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(address: String, storageKeys: [String]) {
        self.address = address
        self.storageKeys = storageKeys
    }

    

    
}

#if compiler(>=6)
extension AccessListItem: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccessListItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AccessListItem {
        return
            try AccessListItem(
                address: FfiConverterString.read(from: &buf), 
                storageKeys: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: AccessListItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.address, into: &buf)
        FfiConverterSequenceString.write(value.storageKeys, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccessListItem_lift(_ buf: RustBuffer) throws -> AccessListItem {
    return try FfiConverterTypeAccessListItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccessListItem_lower(_ value: AccessListItem) -> RustBuffer {
    return FfiConverterTypeAccessListItem.lower(value)
}


public struct Address: Equatable, Hashable {
    public var chain: JovaChain
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chain: JovaChain, value: String) {
        self.chain = chain
        self.value = value
    }

    

    
}

#if compiler(>=6)
extension Address: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAddress: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Address {
        return
            try Address(
                chain: FfiConverterTypeJovaChain.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Address, into buf: inout [UInt8]) {
        FfiConverterTypeJovaChain.write(value.chain, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddress_lift(_ buf: RustBuffer) throws -> Address {
    return try FfiConverterTypeAddress.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddress_lower(_ value: Address) -> RustBuffer {
    return FfiConverterTypeAddress.lower(value)
}


public struct EvmUnsigned: Equatable, Hashable {
    public var chainId: UInt64
    public var nonce: UInt64
    public var to: String
    public var value: String
    public var gasLimit: UInt64
    public var maxFeePerGas: String
    public var maxPriorityFeePerGas: String
    public var data: String
    public var accessList: [AccessListItem]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chainId: UInt64, nonce: UInt64, to: String, value: String, gasLimit: UInt64, maxFeePerGas: String, maxPriorityFeePerGas: String, data: String, accessList: [AccessListItem]) {
        self.chainId = chainId
        self.nonce = nonce
        self.to = to
        self.value = value
        self.gasLimit = gasLimit
        self.maxFeePerGas = maxFeePerGas
        self.maxPriorityFeePerGas = maxPriorityFeePerGas
        self.data = data
        self.accessList = accessList
    }

    

    
}

#if compiler(>=6)
extension EvmUnsigned: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEvmUnsigned: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EvmUnsigned {
        return
            try EvmUnsigned(
                chainId: FfiConverterUInt64.read(from: &buf), 
                nonce: FfiConverterUInt64.read(from: &buf), 
                to: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf), 
                gasLimit: FfiConverterUInt64.read(from: &buf), 
                maxFeePerGas: FfiConverterString.read(from: &buf), 
                maxPriorityFeePerGas: FfiConverterString.read(from: &buf), 
                data: FfiConverterString.read(from: &buf), 
                accessList: FfiConverterSequenceTypeAccessListItem.read(from: &buf)
        )
    }

    public static func write(_ value: EvmUnsigned, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.chainId, into: &buf)
        FfiConverterUInt64.write(value.nonce, into: &buf)
        FfiConverterString.write(value.to, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
        FfiConverterUInt64.write(value.gasLimit, into: &buf)
        FfiConverterString.write(value.maxFeePerGas, into: &buf)
        FfiConverterString.write(value.maxPriorityFeePerGas, into: &buf)
        FfiConverterString.write(value.data, into: &buf)
        FfiConverterSequenceTypeAccessListItem.write(value.accessList, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEvmUnsigned_lift(_ buf: RustBuffer) throws -> EvmUnsigned {
    return try FfiConverterTypeEvmUnsigned.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEvmUnsigned_lower(_ value: EvmUnsigned) -> RustBuffer {
    return FfiConverterTypeEvmUnsigned.lower(value)
}


public struct Signature: Equatable, Hashable {
    public var hex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(hex: String) {
        self.hex = hex
    }

    

    
}

#if compiler(>=6)
extension Signature: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignature: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Signature {
        return
            try Signature(
                hex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Signature, into buf: inout [UInt8]) {
        FfiConverterString.write(value.hex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignature_lift(_ buf: RustBuffer) throws -> Signature {
    return try FfiConverterTypeSignature.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignature_lower(_ value: Signature) -> RustBuffer {
    return FfiConverterTypeSignature.lower(value)
}


public struct SignedTx: Equatable, Hashable {
    public var chain: JovaChain
    public var rawHex: String
    public var txHash: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chain: JovaChain, rawHex: String, txHash: String) {
        self.chain = chain
        self.rawHex = rawHex
        self.txHash = txHash
    }

    

    
}

#if compiler(>=6)
extension SignedTx: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignedTx: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignedTx {
        return
            try SignedTx(
                chain: FfiConverterTypeJovaChain.read(from: &buf), 
                rawHex: FfiConverterString.read(from: &buf), 
                txHash: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SignedTx, into buf: inout [UInt8]) {
        FfiConverterTypeJovaChain.write(value.chain, into: &buf)
        FfiConverterString.write(value.rawHex, into: &buf)
        FfiConverterString.write(value.txHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignedTx_lift(_ buf: RustBuffer) throws -> SignedTx {
    return try FfiConverterTypeSignedTx.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignedTx_lower(_ value: SignedTx) -> RustBuffer {
    return FfiConverterTypeSignedTx.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum BtcMsgScheme: Equatable, Hashable {
    
    case bip322
    case legacy





}

#if compiler(>=6)
extension BtcMsgScheme: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBtcMsgScheme: FfiConverterRustBuffer {
    typealias SwiftType = BtcMsgScheme

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BtcMsgScheme {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bip322
        
        case 2: return .legacy
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BtcMsgScheme, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bip322:
            writeInt(&buf, Int32(1))
        
        
        case .legacy:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBtcMsgScheme_lift(_ buf: RustBuffer) throws -> BtcMsgScheme {
    return try FfiConverterTypeBtcMsgScheme.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBtcMsgScheme_lower(_ value: BtcMsgScheme) -> RustBuffer {
    return FfiConverterTypeBtcMsgScheme.lower(value)
}



public enum FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InvalidMnemonic(message: String)
    
    case InvalidPassphrase(message: String)
    
    case InvalidAddress(message: String)
    
    case UnsupportedChain(message: String)
    
    case MalformedUnsignedTx(message: String)
    
    case MalformedSignableMessage(message: String)
    
    case SigningFailed(message: String)
    
    case Internal(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidMnemonic(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidPassphrase(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .InvalidAddress(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .UnsupportedChain(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .MalformedUnsignedTx(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .MalformedSignableMessage(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .SigningFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .Internal(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InvalidMnemonic(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidPassphrase(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .InvalidAddress(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .UnsupportedChain(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .MalformedUnsignedTx(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .MalformedSignableMessage(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .SigningFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .Internal(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum JovaChain: Equatable, Hashable {
    
    case ethereum
    case polygon
    case bsc
    case arbitrum
    case optimism
    case base
    case bitcoin
    case solana
    case xrp
    case customEvm(chainId: UInt64
    )





}

#if compiler(>=6)
extension JovaChain: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJovaChain: FfiConverterRustBuffer {
    typealias SwiftType = JovaChain

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JovaChain {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ethereum
        
        case 2: return .polygon
        
        case 3: return .bsc
        
        case 4: return .arbitrum
        
        case 5: return .optimism
        
        case 6: return .base
        
        case 7: return .bitcoin
        
        case 8: return .solana
        
        case 9: return .xrp
        
        case 10: return .customEvm(chainId: try FfiConverterUInt64.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: JovaChain, into buf: inout [UInt8]) {
        switch value {
        
        
        case .ethereum:
            writeInt(&buf, Int32(1))
        
        
        case .polygon:
            writeInt(&buf, Int32(2))
        
        
        case .bsc:
            writeInt(&buf, Int32(3))
        
        
        case .arbitrum:
            writeInt(&buf, Int32(4))
        
        
        case .optimism:
            writeInt(&buf, Int32(5))
        
        
        case .base:
            writeInt(&buf, Int32(6))
        
        
        case .bitcoin:
            writeInt(&buf, Int32(7))
        
        
        case .solana:
            writeInt(&buf, Int32(8))
        
        
        case .xrp:
            writeInt(&buf, Int32(9))
        
        
        case let .customEvm(chainId):
            writeInt(&buf, Int32(10))
            FfiConverterUInt64.write(chainId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJovaChain_lift(_ buf: RustBuffer) throws -> JovaChain {
    return try FfiConverterTypeJovaChain.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJovaChain_lower(_ value: JovaChain) -> RustBuffer {
    return FfiConverterTypeJovaChain.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SignableMessage: Equatable, Hashable {
    
    case evmPersonalSign(message: String
    )
    case evmTypedDataV4(json: String
    )
    /**
     * Phase 3 — declared for forward compatibility; returns UnsupportedChain until implemented.
     */
    case solana(messageBase64: String
    )
    case bitcoin(message: String, address: String, scheme: BtcMsgScheme
    )





}

#if compiler(>=6)
extension SignableMessage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignableMessage: FfiConverterRustBuffer {
    typealias SwiftType = SignableMessage

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignableMessage {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .evmPersonalSign(message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .evmTypedDataV4(json: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .solana(messageBase64: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .bitcoin(message: try FfiConverterString.read(from: &buf), address: try FfiConverterString.read(from: &buf), scheme: try FfiConverterTypeBtcMsgScheme.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SignableMessage, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .evmPersonalSign(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .evmTypedDataV4(json):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(json, into: &buf)
            
        
        case let .solana(messageBase64):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(messageBase64, into: &buf)
            
        
        case let .bitcoin(message,address,scheme):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            FfiConverterString.write(address, into: &buf)
            FfiConverterTypeBtcMsgScheme.write(scheme, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignableMessage_lift(_ buf: RustBuffer) throws -> SignableMessage {
    return try FfiConverterTypeSignableMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignableMessage_lower(_ value: SignableMessage) -> RustBuffer {
    return FfiConverterTypeSignableMessage.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum UnsignedTx: Equatable, Hashable {
    
    case evm(tx: EvmUnsigned
    )
    case bitcoin(psbtBase64: String
    )
    /**
     * Phase 3c — declared for forward compatibility; returns UnsupportedChain until implemented.
     */
    case solana(messageBase64: String, recentBlockhash: String
    )
    /**
     * XRPL transaction (Phase 3b): a canonical XRPL JSON object as a string.
     * The signer injects `SigningPubKey` and `TxnSignature`; callers must not
     * pre-populate those fields.
     */
    case xrp(txJson: String
    )





}

#if compiler(>=6)
extension UnsignedTx: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUnsignedTx: FfiConverterRustBuffer {
    typealias SwiftType = UnsignedTx

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UnsignedTx {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .evm(tx: try FfiConverterTypeEvmUnsigned.read(from: &buf)
        )
        
        case 2: return .bitcoin(psbtBase64: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .solana(messageBase64: try FfiConverterString.read(from: &buf), recentBlockhash: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .xrp(txJson: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UnsignedTx, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .evm(tx):
            writeInt(&buf, Int32(1))
            FfiConverterTypeEvmUnsigned.write(tx, into: &buf)
            
        
        case let .bitcoin(psbtBase64):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(psbtBase64, into: &buf)
            
        
        case let .solana(messageBase64,recentBlockhash):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(messageBase64, into: &buf)
            FfiConverterString.write(recentBlockhash, into: &buf)
            
        
        case let .xrp(txJson):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(txJson, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUnsignedTx_lift(_ buf: RustBuffer) throws -> UnsignedTx {
    return try FfiConverterTypeUnsignedTx.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUnsignedTx_lower(_ value: UnsignedTx) -> RustBuffer {
    return FfiConverterTypeUnsignedTx.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAccessListItem: FfiConverterRustBuffer {
    typealias SwiftType = [AccessListItem]

    public static func write(_ value: [AccessListItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAccessListItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AccessListItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [AccessListItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAccessListItem.read(from: &buf))
        }
        return seq
    }
}
/**
 * Generate a new random mnemonic. Returns the word string (12 or 24 words).
 */
public func createMnemonic(bits256: Bool) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_jova_core_ffi_fn_func_create_mnemonic(
        FfiConverterBool.lower(bits256),$0
    )
})
}
/**
 * Return `true` if `addr` is a valid address for `chain`.
 */
public func isValidAddress(addr: String, chain: JovaChain) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_jova_core_ffi_fn_func_is_valid_address(
        FfiConverterString.lower(addr),
        FfiConverterTypeJovaChain_lower(chain),$0
    )
})
}
/**
 * Return `true` if `words` is a valid BIP-39 mnemonic with correct checksum.
 */
public func isValidMnemonic(words: String, passphrase: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_jova_core_ffi_fn_func_is_valid_mnemonic(
        FfiConverterString.lower(words),
        FfiConverterString.lower(passphrase),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_jova_core_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_jova_core_ffi_checksum_func_create_mnemonic() != 44464) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jova_core_ffi_checksum_func_is_valid_address() != 61401) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jova_core_ffi_checksum_func_is_valid_mnemonic() != 1572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jova_core_ffi_checksum_method_jovawallet_address() != 56552) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jova_core_ffi_checksum_method_jovawallet_sign_message() != 15053) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jova_core_ffi_checksum_method_jovawallet_sign_tx() != 22368) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jova_core_ffi_checksum_constructor_jovawallet_from_mnemonic() != 26437) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureJovaCoreFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all